version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatesyle-app
    container_name: chatesyle-app
    restart: unless-stopped
    ports:
      - "8006:80"            # APP_URL in your .env uses port 8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY:-}
      - DB_CONNECTION=mysql
      - DB_HOST=chatesyle-db
      - DB_PORT=3306
      - DB_DATABASE=chatesyle
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - ./:/var/www/html     # mount project for live dev
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-chatesyle
    restart: unless-stopped
    env_file:                      # optional: pick up values from local .env if desired
      - .env
    environment:
      MYSQL_DATABASE: chatesyle
      MYSQL_ROOT_PASSWORD: ""       # empty root password allowed via MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3400:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-chatesyle
    restart: unless-stopped
    environment:
      PMA_HOST: chatesyle-db
      PMA_PORT: 3306
    ports:
      - "8086:80"
    depends_on:
      - chatesyle-db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
